name: 🔵 Feature request
description: Improve the software
title: "[REQUEST] <title>"
labels: [request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing request for this?
    description: Please search to see if a request already exists for the feature you want.
    options:
    - label: I have searched the existing requests.
      required: true
- type: textarea
  attributes:
    label: Request
    description: Tell us about what you want on Atomic.
  validations:
    required: false
- type: textarea
  attributes:
    label: Supporting information
    description: |
      Drawings, screenshots, links to other software...

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false